# Source for Waratah: https://github.com/microsoft/hidtools

[[settings]]
generateCpp = true

[[unit]]
name = 'inch_2'
inch = [0.01, 1.0]

[[unit]]
name = 'second_4'
second = [0.0001, 1.0]

[[usagePage]]
id = 13
name = 'Digitizers'

    [[usagePage.usage]]
    id = 197
    name = 'Device Certification Status Feature Report'
    types = ['SV']

[[applicationCollection]]
usage = ['Digitizers', 'Touch Pad']

    [[applicationCollection.inputReport]]
    id = 1

        # Contacts
        [[applicationCollection.inputReport.logicalCollection]]
        usage = ['Digitizers', 'Finger']
            
            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Touch Valid']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Switch']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Contact Identifier']
            logicalValueRange = [0, 15]

            [[applicationCollection.inputReport.logicalCollection.paddingItem]]
            sizeInBits = 2

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Pressure']
            logicalValueRange = [0, 65535]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'X']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 519]  # 519 is a placeholder
            unit = 'inch_2'

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'Y']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 330]  # 330 is a placeholder
            unit = 'inch_2'

        [[applicationCollection.inputReport.logicalCollection]]
        usage = ['Digitizers', 'Finger']
            
            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Touch Valid']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Switch']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Contact Identifier']
            logicalValueRange = [0, 15]

            [[applicationCollection.inputReport.logicalCollection.paddingItem]]
            sizeInBits = 2

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Pressure']
            logicalValueRange = [0, 65535]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'X']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 519]  # 519 is a placeholder
            unit = 'inch_2'

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'Y']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 330]  # 330 is a placeholder
            unit = 'inch_2'

        [[applicationCollection.inputReport.logicalCollection]]
        usage = ['Digitizers', 'Finger']
            
            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Touch Valid']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Switch']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Contact Identifier']
            logicalValueRange = [0, 15]

            [[applicationCollection.inputReport.logicalCollection.paddingItem]]
            sizeInBits = 2

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Pressure']
            logicalValueRange = [0, 65535]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'X']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 519]  # 519 is a placeholder
            unit = 'inch_2'

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'Y']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 330]  # 330 is a placeholder
            unit = 'inch_2'

        [[applicationCollection.inputReport.logicalCollection]]
        usage = ['Digitizers', 'Finger']
            
            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Touch Valid']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Switch']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Contact Identifier']
            logicalValueRange = [0, 15]

            [[applicationCollection.inputReport.logicalCollection.paddingItem]]
            sizeInBits = 2

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Pressure']
            logicalValueRange = [0, 65535]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'X']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 519]  # 519 is a placeholder
            unit = 'inch_2'

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'Y']
            logicalValueRange = [0, 4095]  # 4095 is a placeholder for 12-bit input
            physicalValueRange = [0, 330]  # 330 is a placeholder
            unit = 'inch_2'

        [[applicationCollection.inputReport.logicalCollection]]
        usage = ['Digitizers', 'Finger']
            
            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Touch Valid']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Switch']
            logicalValueRange = [0, 1]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Contact Identifier']
            logicalValueRange = [0, 15]

            [[applicationCollection.inputReport.logicalCollection.paddingItem]]
            sizeInBits = 2

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Digitizers', 'Tip Pressure']
            logicalValueRange = [0, 65535]

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'X']
            sizeInBits = 16
            physicalValueRange = [0, 519]  # 519 is a placeholder
            unit = 'inch_2'

            [[applicationCollection.inputReport.logicalCollection.variableItem]]
            usage = ['Generic Desktop', 'Y']
            sizeInBits = 16
            physicalValueRange = [0, 330]  # 330 is a placeholder
            unit = 'inch_2'

        [[applicationCollection.inputReport.variableItem]]
        usage = ['Digitizers', 'Scan Time']
        logicalValueRange = [0, 65535]
        physicalValueRange = [0, 65535]
        unit = 'second_4'

        [[applicationCollection.inputReport.variableItem]]
        usage = ['Digitizers', 'Contact Count']
        logicalValueRange = [0, 127]

        # Indicates Button State for Touchpad button integrated with digitizer
        # [[applicationCollection.inputReport.variableItem]]
        # usage = ['Button', 'Button 1']
        # logicalValueRange = [0, 1]

    [[applicationCollection.featureReport]]
    id = 2

        [[applicationCollection.featureReport.variableItem]]
        usage = ['Digitizers', 'Contact Count Maximum']
        logicalValueRange = [0, 15]

        [[applicationCollection.featureReport.variableItem]]
        usage = ['Digitizers', 'Pad Type']
        logicalValueRange = [0, 15]

    [[applicationCollection.featureReport]]
    id = 3

        [[applicationCollection.featureReport.variableItem]]
        usage = ['Digitizers', 'Device Certification Status Feature Report']
        logicalValueRange = [0, 255]
        count = 256

[[applicationCollection]]
usage = ['Generic Desktop', 'Mouse']

    [[applicationCollection.inputReport]]
    id = 4

        [[applicationCollection.inputReport.physicalCollection]]
        usage = ['Generic Desktop', 'Pointer']

            [[applicationCollection.inputReport.physicalCollection.variableItem]]
            usageRange = ['Generic Desktop', 'X', 'Y']
            sizeInBits = 8
            logicalValueRange = 'maxSignedSizeRange'
            reportFlags = ['relative']

            [[applicationCollection.inputReport.physicalCollection.variableItem]]
            usage = ['Generic Desktop', 'Wheel']
            sizeInBits = 8
            logicalValueRange = 'maxSignedSizeRange'
            reportFlags = ['relative']

            [[applicationCollection.inputReport.physicalCollection.variableItem]]
            usage = ['Consumer', 'AC Pan']
            sizeInBits = 8
            logicalValueRange = 'maxSignedSizeRange'
            reportFlags = ['relative']

            [[applicationCollection.inputReport.physicalCollection.variableItem]]
            usageRange = ['Button', 'Button 1', 'Button 8']
            logicalValueRange = [0, 1]
