#pragma once

#define PRECISION_TOUCHPAD_RDY_PIN GP2  // D0
#define RESERVED_D_WIRES (const pin_t []){GP2, }
#define AZOTEQ_IQS5XX_TPS43
#define PRECISION_TOUCHPAD_DEBUG
#define POINTING_DEVICE_DEBUG
