OPT_DEFS += -DPRODUCT=\"P2PPCB\ Precision\ Touchpad\ Example\"
OPT_DEFS += -DPRODUCT_ID=0x965f

PRECISION_TOUCHPAD_ENABLE = yes
PRECISION_TOUCHPAD_DRIVER = azoteq_iqs5xx
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
