OPT_DEFS += -DPRODUCT=\"P2PPCB\ Precision\ Touchpad\ Example\"
OPT_DEFS += -DDEVICE_VER=0x0005

PRECISION_TOUCHPAD_ENABLE = yes
PRECISION_TOUCHPAD_DRIVER = azoteq_iqs5xx
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
